---
apiVersion: v1                # API version
kind: Service                 # Type of the kubernetes resource
metadata:
  name: employee-jdbc-server    # Name of the kubernetes resource
  labels:                     # Labels that will be applied to this resource
    app: employee-jdbc-server
spec:
  type: LoadBalancer              # The service will be exposed by opening a Port on each node and proxying it.
  selector:
    app: employee-jdbc-server   # The service exposes Pods with label `app=employee-jdbc-server`
  ports:                      # Forward incoming connections on port 8080 to the target port 8080
  - name: http
    port: 80
    targetPort: 8080

